Repository googleinterns/dagger-query, pull requests merged in 2020-08, with the labels that each got.

#6 Implemented an algorithm for traversing binding graph
  project/BUILD
  project/src/com/google/daggerquery/BUILD
  project/src/com/google/daggerquery/plugin/BUILD
  project/src/com/google/daggerquery/plugin/GraphConverter.java
  project/src/com/google/daggerquery/plugin/QueryPlugin.java
  project/src/com/google/daggerquery/protobuf/BUILD
  project/tests/com/google/daggerquery/plugin/BUILD
  project/tests/com/google/daggerquery/plugin/GraphConverterTest.java
  project/third_party/java/guava/BUILD
  project/third_party/java/junit/BUILD
  project/workspace_defs.bzl
Labels: enhancement

#8 Added presubmit.yml file required for opening CI issue
  .bazelci/presubmit.yml
Labels: enhancement

#9 Specified working directory and removed bazel version constraint
  .bazelci/presubmit.yml
Labels: bug, enhancement

#10 Added bazel rule with example to test graph serialization
  project/src/com/google/daggerquery/BUILD
  project/src/com/google/daggerquery/dagger_query_textproto.bzl
  project/src/com/google/daggerquery/plugin/QueryPlugin.java
Labels: enhancement

#11 Fixing CI with buildkite
  .bazelci/presubmit.yml
  .gitignore
  project/src/com/google/daggerquery/protobuf/autogen/BindingGraphProto.java
  project/src/com/google/daggerquery/protobuf/autogen/DependencyProto.java
  project/workspace_defs.bzl
Labels: bug, enhancement

#12 Supported DEPS query
  project/src/com/google/daggerquery/executor/BUILD
  project/src/com/google/daggerquery/executor/QueryExecutor.java
  project/src/com/google/daggerquery/executor/models/BUILD
  project/src/com/google/daggerquery/executor/models/Query.java
  project/src/com/google/daggerquery/executor/services/BUILD
  project/src/com/google/daggerquery/executor/services/SourcesLoader.java
  project/tests/com/google/daggerquery/executor/models/BUILD
  project/tests/com/google/daggerquery/executor/models/QueryTest.java
  project/tests/com/google/daggerquery/plugin/GraphConverterTest.java
  project/workspace_defs.bzl
Labels: enhancement

#13 Automagically generate protobufs using Bazel's java_proto_library rule.
  .gitignore
  README.md
  project/WORKSPACE
  project/src/com/google/daggerquery/plugin/BUILD
  project/src/com/google/daggerquery/protobuf/BUILD
  project/src/com/google/daggerquery/protobuf/autogen/BindingGraphProto.java
  project/src/com/google/daggerquery/protobuf/autogen/DependencyProto.java
  project/src/com/google/daggerquery/protobuf/binding_graph.proto
  project/tests/com/google/daggerquery/plugin/BUILD
  project/workspace_defs.bzl
Labels: enhancement

#14 Fix broken build dependencies.
  project/src/com/google/daggerquery/executor/BUILD
  project/src/com/google/daggerquery/executor/models/BUILD
  project/src/com/google/daggerquery/executor/services/BUILD
  project/tests/com/google/daggerquery/executor/models/BUILD
Labels: bug fix, enhancement

#15 Supported ALLPATHS query 🚀
  project/src/com/google/daggerquery/executor/models/Query.java
  project/tests/com/google/daggerquery/executor/models/QueryTest.java
  project/tests/com/google/daggerquery/plugin/GraphConverterTest.java
Labels: enhancement

#16 Added missing Guava dependency
  project/src/com/google/daggerquery/executor/models/BUILD
Labels: bug fix

#18 Made a message in exception more detailed and user-friendly ✔️
  project/src/com/google/daggerquery/executor/models/Query.java
Labels: documentation, enhancement

#20 Adds Javadoc where it was missing
  project/src/com/google/daggerquery/executor/models/Query.java
  project/src/com/google/daggerquery/plugin/QueryPlugin.java
Labels: documentation

#17 Serialize all binding graphs into different files and pack them into one .zip archive 👩‍💻
  project/src/com/google/daggerquery/dagger_query_textproto.bzl
  project/src/com/google/daggerquery/plugin/QueryPlugin.java
Labels: enhancement

#21 Supported SOMEPATH query 🔫
  project/src/com/google/daggerquery/executor/models/Query.java
  project/tests/com/google/daggerquery/executor/models/QueryTest.java
Labels: enhancement

#22 Changed command to avoid including files from current directory
  project/src/com/google/daggerquery/dagger_query_textproto.bzl
Labels: bug fix, enhancement

#19 Supported unzipping archive in a command-line app
  project/src/com/google/daggerquery/executor/BUILD
  project/src/com/google/daggerquery/executor/QueryExecutor.java
  project/src/com/google/daggerquery/executor/services/BUILD
  project/src/com/google/daggerquery/executor/services/SourcesLoader.java
Labels: enhancement

#24 Supported typos fixer ⚙️
  project/WORKSPACE
  project/src/com/google/daggerquery/executor/QueryExecutor.java
  project/src/com/google/daggerquery/executor/models/BUILD
  project/src/com/google/daggerquery/executor/models/MisspelledNodeNameException.java
  project/src/com/google/daggerquery/executor/models/Query.java
  project/tests/com/google/daggerquery/executor/models/QueryTest.java
Labels: enhancement
